### ISSUE TITLE
specifying binarization method in python

### ISSUE THREAD

**Issue by SB2020-eye** [brandonmpetty/Doxa#15]
Hello!

I'm trying to specify binarization methods and/or use all at once using demo.py as my starter template.

Here's the latest that I tried:
```
# Loop through all binarization algorithms
binarize_algos = [BERNSEN, NIBLACK, SAUVOLA, WOLF, NICK, SU, TRSINGH, BATAINEH, ISAUVOLA, WAN, GATOS]
for ba in binarize_algos:
    algo = doxapy.Binarization(doxapy.Binarization.Algorithms.ba)
    algo.initialize(grayscale_image)
    algo.to_binary(binary_image, {"window": 75, "k": 0.2}) # algorithm params are optional

    # Display our resulting image
    Image.fromarray(binary_image).show()
```

I also tried with the list's methods in quotes, mixed in with 3 or so variations on this line:
    `algo = doxapy.Binarization(doxapy.Binarization.Algorithms.ba)`
(str(ba), for example, pluses (for both str(ba) and just ba like you see above)

Any idea what I'm doing wrong?

**Comment by brandonmpetty** [comment]
You can do something like this:
```python
for ba in doxapy.Binarization.Algorithms.__members__.values():
    algo = doxapy.Binarization(ba)
```
An issue you may run into is that each algorithm needs to be tuned with its own set of parameters.
You can either omit the parameters, and stick with the library defaults, or you can create a dictionary that looks up the custom parameters in the loop for the algorithm.  I hope that helps!
