### ISSUE TITLE
skewed large images

### ISSUE THREAD

**Issue by kevingnet** [brandonmpetty/Doxa#25]
Thank you for this great library, it's very well put together and easy to use and understand. I'm doing a personal project, restarting after a very long time and this library will save me time so I can focus on what I'm doing.

When I use a large file, the binary result shows skewed lines thorough out the whole file. After I scaled the file in half it worked ok. The original file was 1800x1200 pixels.

**Comment by bpetty-interlace** [comment]
Sorry to hear about the issue @kevingnet
Could you tell me exactly what you are doing?
Specifically:

- Is this happening in C++ or one of the Bindings?
- How are you reading your image into the framework?
- I assume this is happening with any binarization method, or is it a specific one?

With some of the more recent optimizations, all of the algorithms (except an experimental one) have been retooled to support much larger images, something not possible with the standard Integral Image technique.  I'll check it out... thanks for letting me know!

**Comment by brandonmpetty** [comment]
Sorry to hear about the issue @kevingnet 
Could you tell me exactly what you are doing?
Specifically:

- Is this happening in C++ or one of the Bindings?
- How are you reading your image into the framework?
- I assume this is happening with any binarization method, or is it a specific one?

With some of the more recent optimizations, all of the algorithms (except an experimental one) have been retooled to support much larger images, something not possible with the standard Integral Image technique. I'll check it out... thanks for letting me know!

**Comment by kevingnet** [comment]
Hi Brandon,

actually it works fine. my bad. the issue was that when i convert the image
usim gimp the header has a label, however when i use convert fro graphics
magic there is no label in the conversion,  perhaps that's why,  i haven't
investigated more, but I'm glad it's working really well. great job and
thanks for the prompt reply.

**Comment by brandonmpetty** [comment]
Awesome!  Glad to hear.
I just converted a 4554x5247 JPG (6.3MB) into an uncompressed PPM (68.3MB) and the framework successfully converted it to a Binary PBM (2.85MB) file without issue.
