### ISSUE TITLE
Malformed output with “zebra stripes” due to a bug in `PNM.hpp`

### ISSUE THREAD

**Issue by D-Vindy** [brandonmpetty/Doxa#36]
Hello,

I'm testing Doxa for converting color or grayscale book scans to bilevel images. I would say that 95% of time, it works, but 5% of time, Doxa produces malformed output with “zebra stripes” for lack of a better term. Here is how this output looks:

![output pbm](https://github.com/brandonmpetty/Doxa/assets/146453846/7ad8fa2c-3d58-48d8-a41e-5e9a4b69ba91)

The code I’m using is very basic:

```
        Doxa::Image doxaGsImage = Doxa::PNM::Read(input);
        Doxa::ISauvola::UpdateToBinary(doxaGsImage);
        Doxa::PNM::Write(doxaGsImage, output);
```

Thank you in advance for looking into this issue.

Please find attached, as ZIP file, a sample showing the problem. The ZIP file contains:

- input.png — the original book scan
- input.png.ppm — the original converted to PPM, so it can be opened using `Doxa::PNM::Read`
- output.pbm — the malformed output

[Sample.zip](https://github.com/brandonmpetty/Doxa/files/13641808/Sample.zip)

**Comment by brandonmpetty** [comment]
Thank you!  I will try to get this fixed as soon as possible.

**Comment by brandonmpetty** [comment]
Your solution has been implemented, with unit test coverage.  Thanks again!
