### ISSUE TITLE
`#include "Morphology.hpp"` is missing from `Wan.hpp`

### ISSUE THREAD

**Issue by D-Vindy** [brandonmpetty/Doxa#37]
Hello,

The Wan algorithm won't compile, because it makes uses of a morphology function:

`Morphology::Dilate(maxImage, Algorithm::grayScaleImageIn, windowSize);`

and yet, `#include "Morphology.hpp"` is missing from `Wan.hpp`.

Luckily, the fix is easy. The relevant include simply has to be added.

Hope this helps!

**Comment by brandonmpetty** [comment]
Thank you.  This has been resolved.
