### ISSUE TITLE
Incorrect binarization algorythm in Demo Application

### ISSUE THREAD

**Issue by HubertMichalakZUT** [brandonmpetty/Doxa#9]
https://github.com/brandonmpetty/Doxa/blob/c693465150fef7887e1ddcebbd52b4ab287e8838/Demo/BinaryImageConverter/BinaryImageConverter.cpp#L180

Should be "bataineh" and not "trsingh"

**Comment by bpetty-formfast** [comment]
Thanks for bringing that to my attention.  I'll try to correct it shortly.
